name: pymox tests

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests and collect coverage
        run: pytest -vv --cov=mox --cov-branch --cov-report=xml test

      - name: Prepare coverage token
        if: success() && github.repository == 'ivancrneto/pymox'
        run: cp .github/codecov-token.txt .

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "codecov-token.txt"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          flags: pymox-tests-${{ matrix.python-version }}
          fail_ci_if_error: true
          verbose: true
          token: ${{ steps.read_file.outputs.contents }}
